name: release storybook
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install & build
        run: |
          npm ci
          npm run build-storybook
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: storybook-static
          clean: true
